### PR TITLE
add "export" to all interfaces and types

### PR DESCRIPTION
**Pull request by orblazer**
Hello,
I have add `export` to all interfaces and types for enable to use that in https://github.com/nuxt-community/modules/tree/master/packages/toast
In same time i have implement the PR #116.

Thanks

### CODE REVIEW

**Comment by RomainLanz** [comment]
Hey @shakee93! 👋 

Any plan to merge this?

**Comment by Nfinished** [comment]
Really need this, gamebreaking for TS components without.

**Comment by drewstewart** [comment]
Still waiting for this to happen. Also waiting for the ts fixes for `global: any` and `register(name: string, message: string | ((payload:any) => string), ...` to be released on npm.

Since @shakee93 seems non-responsive to all issues raised in past 6 months (unfortunate because he's done a great job with this lib) what options do we have? fork it and release into npm?

**Comment by Nfinished** [comment]
Start poking him on twitter?

**Comment by orblazer** [comment]
@Nfinished I have send an PM just now on twitter.

**Pull request merged**
