### PR TITLE
Accept custom class in toast icons

### PR DESCRIPTION
**Pull request by Barterr**
Added another option to iconPack, custom-class.
With this the icon/icon.name is used as direct classes to the icons, so you can use any class based icon set, like fontawesome5 for example like this:

this.$toasted.show('test', { icon: { name: 'fal fa-check fa-spin' }, type: 'error' });

This will render a toast with an icon as `<i class="fal fa-check fa-spin"></i>`

Also had to fix the webpack config for path so I could build, it now needs an absolute path in output.path

### CODE REVIEW

**Comment by jakelumetta** [comment]
Looking forward to this one!

**Comment by thminhVN** [comment]
Hi @Barterr, Could you help us merge this PR because we are needing this feature?

**Comment by Barterr** [comment]
Hey @thminhVN, I only submitted the PR, @shakee93 is the one that can approve it so it can be merged

**Comment by Rstyl3** [comment]
@shakee93 merging this anytime soon?

**Comment by johnwhelchel** [comment]
@shakee93 Please merge!

**Comment by shakee93** [comment]
Sorry for the extreme delay. merged this. will publish to npm as a minor version.

thanks.

**Comment by Rstyl3** [comment]
@Barterr  message seems to work fine but action icon shows blank i tags(no class include ).

**Comment by Rstyl3** [comment]
@Barterr @shakee93 Found the problem. It seems you misstyped the variable in action.icon:
This:
el.classList.add(className)
Should be:
iel.classList.add(className)

Who ever needs a fix for this, I managed to change the code in vue-toasted.min.js file in line 1092 (found in node_modules/vue-toasted/dist)
Before:
```javascript
case "custom-class":
    "string" == typeof t.icon ? t.icon.split(" ").forEach(function (t) {
        n.classList.add(t)
    }) : Array.isArray(t.icon) && t.icon.forEach(function (t) {
        n.classList.add(t.trim())
    });
    break;
```
After:
```javascript
case "custom-class":
    var o = t.icon.name ? t.icon.name : t.icon;
    "string" == typeof o ? o.split(" ").forEach(function (t) {
        r.classList.add(t)
    }) : Array.isArray(t.icon) && t.icon.forEach(function (t) {
        r.classList.add(t.trim())
    });
    break;
```

**Pull request merged**
