### PR TITLE
Improve accessibility of actions

### PR DESCRIPTION
**Pull request by davidsandoz**
The actions are always using the anchor element `<a>`, regardless whether it is an navigation action or not.

The anchor element should be used only if the action has an `href` attribute. Otherwise a `<button>` must be used.

This PR adds this check and also resets the style of the button so that it visually doesn't change.

### CODE REVIEW

**Comment by shakee93** [comment]
can you please fix this conflict with the latest version. if so i can accept this pull.

thanks

**Comment by davidsandoz** [comment]
@shakee93 Conflicts have been resolved.

**Comment by shakee93** [comment]
Thanks 🙏 Merged !

**Comment by davidsandoz** [comment]
Thanks @shakee93! Do you have an ETA for the next release?

I know I'm not really in a good position to ask this, looking at how long it took me to finally get to fix those conflicts 😅

**Pull request merged**
